# Generated by Django 4.1.2 on 2022-10-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auctions",
            "0003_remove_bids_bid_value_remove_bids_bid_value_currency_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="current_price",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name="listings",
            name="start_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
