# Generated by Django 4.1.2 on 2022-10-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_listings_current_price_listings_start_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="listings",
            name="category",
            field=models.CharField(default=("ETC", "Everything Else"), max_length=3),
        ),
        migrations.AlterField(
            model_name="user",
            name="cellphone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="postcode",
            field=models.CharField(max_length=16),
        ),
    ]
