# Generated by Django 4.1.2 on 2022-10-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_listings_closed_alter_listings_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listings",
            name="current_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
