# Generated by Django 4.1.2 on 2022-11-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_listings_current_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listings",
            name="bidders",
        ),
        migrations.RemoveField(
            model_name="listings",
            name="quantity",
        ),
    ]
