# Generated by Django 4.1.2 on 2022-11-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_remove_listings_bidders_remove_listings_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listings",
            name="current_price",
        ),
        migrations.RemoveField(
            model_name="listings",
            name="number_of_bids",
        ),
        migrations.RemoveField(
            model_name="listings",
            name="watchers",
        ),
    ]
