# Generated by Django 4.1.2 on 2022-11-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_remove_listings_current_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bids",
            old_name="auction_id",
            new_name="auction",
        ),
        migrations.RenameField(
            model_name="bids",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="comments",
            old_name="listing_id",
            new_name="listing",
        ),
        migrations.RenameField(
            model_name="comments",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="listings",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="watches",
            old_name="listing_id",
            new_name="listing",
        ),
        migrations.RenameField(
            model_name="watches",
            old_name="user_id",
            new_name="user",
        ),
    ]
