# Generated by Django 4.1.2 on 2022-11-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_rename_auction_id_bids_auction_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bids",
            old_name="auction",
            new_name="listing",
        ),
        migrations.AlterField(
            model_name="listings",
            name="start_price",
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=19),
        ),
    ]
