# Generated by Django 4.1.2 on 2022-11-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_rename_auction_bids_listing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bids",
            name="bid_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
