# Generated by Django 4.1.2 on 2022-11-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_bids_bid_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bids",
            name="bid_value",
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
