# Generated by Django 4.2 on 2023-06-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_userfollowing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
